### ISSUE TITLE
[RFC] Support async handler on thread function

### ISSUE THREAD

**Issue by praswicaksono** [duart38/Thread#3]
I have proposal to make async handler works inside thread, Here is sample of async handler

```ts
import Thread from "../Thread.ts";

let thread = new Thread<number>(async (e: MessageEvent) => {
  console.log("Worker: Message received from main script");
  const result = e.data[0] * e.data[1];
  await new Promise((resolve) => setTimeout(resolve, 5 * 1000))
  if (isNaN(result)) {
    return 0;
  } else {
    console.log("Worker: Posting message back to main script");
    return (result);
  }
}, "module");

thread.onMessage((e) => {
  console.log(`recived back from thread: ${e}`);
});
thread.postMessage([10, 12]);
thread.postMessage([10, 10]);

//thread.stop();

```

It handy to have async handler so I can use await inside those function. I can prepare a PR if you want  to implement this

**Comment by duart38** [comment]
Hey @praswicaksono looks good to me. Did you want to implement this yourself? if so you may go ahead and fork/open a PR.
If you wanted me to implement it instead just let me know and I'll try some things out
