### ISSUE TITLE
Unable to import local files in threads

### ISSUE THREAD

**Issue by sudokit** [duart38/Thread#8]
consider this:
```typescript
import Thread from "https://deno.land/x/Thread@v4.1.0/Thread.ts";
import { Cat } from "./cat.ts";

const nWorkers = Math.max(Math.floor(navigator.hardwareConcurrency * 0.8), 2);


const threads: Array<Thread> = [];
for (let i = 0; i < nWorkers; ++i) {
  threads.push(
    new Thread<number | undefined, string>(
      (e) => {
        if (e.data.length === 0 || !e.data.length) return;
        const serializer = new Serializer({ classes: { Cat } });
        console.info(e.data);
        const cat: Cat = serializer.deserialize(e.data);
        cat.meow();
        return 0;
      },
      "module",
      [
        'import { Cat } from "./cat.ts"',
        'import { Serializer } from "https://deno.land/x/superserial/mod.ts"',
      ],
    ),
  );
}

let i = 0;
for (const thread of threads) {
  const cat = new Cat(`Matt${i}`);
  thread.onMessage((e) => {
    console.info(`thread -> ${i} : ${e}`);
    ++i;
    thread.stop();
  }).postMessage(serializer.serialize(cat));
}
```

It tries to import ```{ Cat }``` from ```Download https://deno.land/x/Thread@v4.1.0/cat.ts (1/2)```???
I have no idea why it tries fetching it from there. Tried to debug it but i have no idea at which point it appends this library to it...

**Comment by duart38** [comment]
I took a look at it and it seems like the issue only appears when importing the Thread library from a url. I'll continue to try some stuff. 
A temporary fix for now would be to locally download and use the library, so:
```ts
import Thread from "./Thread.ts";
```

**Comment by sudokit** [comment]
Ah so the problem is caused by the main file importing the thread library? Huuh thats bizarre :p. But thanks ill try that!!

**Comment by duart38** [comment]
@sudokit Try the latest version (4.2.0), I believe it should be fixed.

I've also added a debug mode to the library; hopefully this helps with any future problems

**Comment by sudokit** [comment]
Yepps works noww! Thank you!
